# Generated by Django 5.1.2 on 2024-10-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField()),
                ('customer_id', models.PositiveIntegerField()),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=50)),
                ('card_type', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('enabled_prompt', models.BooleanField(default=False)),
                ('pin_number', models.CharField(max_length=10)),
                ('pin_prompt', models.BooleanField(default=False)),
                ('prompt_vehicle', models.PositiveIntegerField(default=0)),
                ('driver_prompt', models.PositiveIntegerField(default=0)),
                ('projectnum_prompt', models.BooleanField(default=False)),
                ('odo_prompt', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Tag',
                'verbose_name_plural': 'Client Tags',
                'db_table': 'client_tags',
                'managed': False,
            },
        ),
    ]
